export const ORGANIZATION_NAME_MIN = 5
export const ORGANIZATION_URI_MIN = 3

export const PHOTOS_REFETCH_DELAY_MS = 1000
export const PHOTOS_REFETCH_EXTENDED_DELAY_MS = 3000
export const PHOTOS_REFETCH_MAX_TIMEPERIOD_MS = 1000 * 10

export const ALBUM_REFETCH_DELAY_MS = 1000
export const ALBUM_REFETCH_EXTENDED_DELAY_MS = 3000
export const ALBUM_REFETCH_MAX_TIMEPERIOD_MS = 1000 * 10
