import { WebPhoto } from '../services/api'
import { RacingEvent } from '../services/api/generated'
import { getDateString } from './utils'

export const previewEvents: Array<RacingEvent> = [
  {
    id: '1',
    name: 'Édition 2022',
    createdDate: getDateString(new Date(0)),
    updatedDate: getDateString(new Date(0)),
    eventDate: getDateString(new Date(2021, 6, 1)),
    image: '/images/sampleEventPhoto.png',
    organisationId: '',
    photoCount: 1648,
    uri: '',
  },
  {
    id: '2',
    name: 'Édition 2021',
    createdDate: getDateString(new Date(0)),
    updatedDate: getDateString(new Date(0)),
    eventDate: getDateString(new Date(2021, 6, 1)),
    image: '/images/sampleEventPhoto.png',
    organisationId: '',
    photoCount: 1322,
    uri: '',
  },
]

export const previewWebPhotos: Array<WebPhoto> = [
  {
    id: '1',
    organizationId: '',
    eventId: '',
    albumId: '',
    bibNumbers: [],
    haveBibsBeenChecked: true,
    width: 0,
    height: 0,
    portrait: false,
    previewImageUrl: '/images/sampleRunnerPhoto.png',
    price: 0,
    name: '',
  },
  {
    id: '2',
    organizationId: '',
    eventId: '',
    albumId: '',
    bibNumbers: [],
    haveBibsBeenChecked: true,
    width: 0,
    height: 0,
    portrait: false,
    previewImageUrl: '/images/sampleRunnerPhoto.png',
    price: 0,
    name: '',
  },
  {
    id: '3',
    organizationId: '',
    eventId: '',
    albumId: '',
    bibNumbers: [],
    haveBibsBeenChecked: true,
    width: 0,
    height: 0,
    portrait: false,
    previewImageUrl: '/images/sampleRunnerPhoto.png',
    price: 0,
    name: '',
  },
  {
    id: '4',
    organizationId: '',
    eventId: '',
    albumId: '',
    bibNumbers: [],
    haveBibsBeenChecked: true,
    width: 0,
    height: 0,
    portrait: false,
    previewImageUrl: '/images/sampleRunnerPhoto.png',
    price: 0,
    name: '',
  },
  {
    id: '5',
    organizationId: '',
    eventId: '',
    albumId: '',
    bibNumbers: [],
    haveBibsBeenChecked: true,
    width: 0,
    height: 0,
    portrait: false,
    previewImageUrl: '/images/sampleRunnerPhoto.png',
    price: 0,
    name: '',
  },
  {
    id: '6',
    organizationId: '',
    eventId: '',
    albumId: '',
    bibNumbers: [],
    haveBibsBeenChecked: true,
    width: 0,
    height: 0,
    portrait: false,
    previewImageUrl: '/images/sampleRunnerPhoto.png',
    price: 0,
    name: '',
  },
  {
    id: '7',
    organizationId: '',
    eventId: '',
    albumId: '',
    bibNumbers: [],
    haveBibsBeenChecked: true,
    width: 0,
    height: 0,
    portrait: false,
    previewImageUrl: '/images/sampleRunnerPhoto.png',
    price: 0,
    name: '',
  },
  {
    id: '8',
    organizationId: '',
    eventId: '',
    albumId: '',
    bibNumbers: [],
    haveBibsBeenChecked: true,
    width: 0,
    height: 0,
    portrait: false,
    previewImageUrl: '/images/sampleRunnerPhoto.png',
    price: 0,
    name: '',
  },
  {
    id: '9',
    organizationId: '',
    eventId: '',
    albumId: '',
    bibNumbers: [],
    haveBibsBeenChecked: true,
    width: 0,
    height: 0,
    portrait: false,
    previewImageUrl: '/images/sampleRunnerPhoto.png',
    price: 0,
    name: '',
  },
  {
    id: '10',
    organizationId: '',
    eventId: '',
    albumId: '',
    bibNumbers: [],
    haveBibsBeenChecked: true,
    width: 0,
    height: 0,
    portrait: false,
    previewImageUrl: '/images/sampleRunnerPhoto.png',
    price: 0,
    name: '',
  },
]
