import * as functions from "firebase-functions"
import express from "express"
import cors = require("cors")
import { generateApiDocs } from "./middleware/docs"
import { errorHandler } from "./middleware/errorHandler"
import { RegisterRoutes } from "./routes"

const runningLocally = process.env.FUNCTIONS_EMULATOR === "true"

// Express app initialization + standard basic middleware
const app = express()
app.use(cors())
app.use(
	express.urlencoded({
		extended: true,
	})
)
app.use(express.json())

if (runningLocally) {
	// Swagger UI available at /docs
	generateApiDocs(app)
}

// Register routes automatically generated by Tsoa
RegisterRoutes(app)

app.use(errorHandler)

export const api = functions.https.onRequest(app)
